# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: "2.1"
services:

# creating my sql database.
  databasemysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: databasemysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ProductEngg
      MYSQL_PASSWORD: root
    networks:
      - balaweblognetwork

  # container for coupon serice
  couponservice:
      build: 
        dockerfile: Dockerfile
        context:  "./couponservice"
      ports:
       - "8001:8001"
      container_name: couponservice
      depends_on:
        - databasemysql
      networks:
        - balaweblognetwork
      volumes:
        - balaweblogvolume:/var/lib

  # container for product serice
  productservice:
    build: 
      dockerfile: Dockerfile
      context:  "./productservice"
    ports:
     - "8002:8002"
    container_name: productservice
    depends_on:
      - databasemysql
      - configserver
    networks:
      - balaweblognetwork
    volumes:
      - balaweblogvolume:/var/lib

  # enable eureka server for service discovery
  eurekaserver:
    build: 
      dockerfile: Dockerfile
      context:  "./eurekaserver"
    ports:
     - "8761:8761"
    container_name: eurekaserver
    networks:
      - balaweblognetwork
    volumes:
      - balaweblogvolume:/var/lib

  
  # enable zuulproxy for api gateway 
  zuulproxy:
    build: 
      dockerfile: Dockerfile
      context:  "./zuulproxy"
    ports:
     - "8765:8765"
    container_name: zuulproxy
    networks:
      - balaweblognetwork
    volumes:
      - balaweblogvolume:/var/lib
  
  # zipkin for distrubuted tracking dashboard

  zipkin:
    image: openzipkin/zipkin-slim
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - balaweblognetwork
    volumes:
      - balaweblogvolume:/var/lib


  # config server 
  configserver:
    build: 
      dockerfile: Dockerfile
      context:  "./configserver"
    ports:
    - "8888:8888"
    container_name: configserver
    networks:
      - balaweblognetwork
    volumes:
      - balaweblogvolume:/var/lib 

  # spring cloud bus - rabbitmq
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - balaweblognetwork
    volumes:
      - balaweblogvolume:/var/lib 

networks:
  balaweblognetwork:
    driver: bridge
volumes:
  balaweblogvolume: